name: jbuti_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  get_storage: ^2.0.3
  iconly: ^1.0.1
  http: ^0.13.5
  modal_progress_hud_nsn: ^0.3.0
  extended_image: ^6.3.4
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  cloud_firestore: ^4.3.1
  firebase_messaging: ^14.2.1
  permission_handler: ^10.2.0
  custom_pop_up_menu: ^1.2.4
  giphy_picker: ^3.0.1
  photo_view: ^0.14.0
  image_picker: ^0.8.6+1
  firebase_storage: ^11.0.10
  bubble: ^1.2.1
  flutter_ringtone_player: ^3.2.0
  flutter_svg: ^1.1.6
  logger: ^1.1.0
  fluttertoast: ^8.1.2
  cached_network_image: ^3.2.3
  intl: ^0.17.0
  curved_navigation_bar: ^1.0.3
  focused_menu: ^1.0.5
  dropdown_search: ^5.0.5
  like_button: ^2.0.5
  url_launcher: ^6.1.8
  flutter_local_notifications: ^13.0.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_launcher_icons: 
  flutter_native_splash: 

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.jpg"
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/locales/
    - assets/icons/


